name: Dependency Review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Dependency Review pull request range
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}
          fail-on-severity: moderate
          warn-only: false
      - name: Dependency Review push range
        if: github.event_name == 'push'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          base-ref: ${{ github.event.before }}
          head-ref: ${{ github.sha }}
          fail-on-severity: moderate
          warn-only: false
      - name: Dependency Review merge group range
        if: github.event_name == 'merge_group'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          base-ref: ${{ github.event.merge_group.base_sha }}
          head-ref: ${{ github.event.merge_group.head_sha }}
          fail-on-severity: moderate
          warn-only: false
