name: Security (SAST)
on:
  push:
    branches: [main, develop]
  pull_request:
  schedule: [{cron: "0 2 * * *"}]
jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.1
      - uses: github/codeql-action/init@0daab03d71ff584ef619d027a3fd9146679c5d84
        with:
          languages: javascript-typescript, python
      - uses: github/codeql-action/analyze@0daab03d71ff584ef619d027a3fd9146679c5d84
